trigger:
  branches:
    exclude:
    - '*'
  tags:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'
steps:
- task: Docker@2
  displayName: Login
  inputs:
    containerRegistry: 'docker-hub-zer0b0t'
    command: 'login'
- task: CmdLine@2
  displayName: Build
  inputs:
    script: |
      set -ex
      VERSION=$(git describe --exact-match --tags $(Build.SourceVersion))
      docker run --privileged --rm tonistiigi/binfmt --install arm64
      docker run --privileged --rm tonistiigi/binfmt
      docker buildx create --use
      docker buildx build --platform linux/amd64,linux/arm64 \
        -t 00security/kafka-kraft:${VERSION} \
        -t 00security/kafka-kraft:latest \
        --push \
        docker/